name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
          work_in_root_file_dir: true
          output_directory: build

      - name: Delete older releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create new release and upload PDF
        uses: softprops/action-gh-release@v1
        with:
          tag_name: pdf-release
          name: "cv.pdf"
          body: "Compiled CV PDF"
          files: build/main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
